import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowUpRight, Sparkles } from 'lucide-react'
import { services } from '@/lib/content'

export const metadata: Metadata = { title: 'Services | Aronia Dynamics', description: 'Strategy, design, engineering, AI, data, and growth services for ambitious teams.' }

export default function ServicesPage() {
  return <main className="min-h-screen bg-background text-foreground"><nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-7 lg:px-10"><Link href="/" className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Sparkles size={18} /></span><span className="font-mono text-sm font-semibold tracking-[.18em]">ARONIA<span className="text-primary">.</span></span></Link><Link href="/contact" className="inline-flex items-center gap-2 rounded-full border border-border px-4 py-2 text-sm hover:border-primary/70 hover:text-primary">Let&apos;s talk <ArrowUpRight size={15} /></Link></nav><section className="mx-auto max-w-7xl px-6 pb-28 pt-16 lg:px-10 lg:pt-24"><p className="eyebrow">Capabilities / 03</p><h1 className="mt-5 max-w-4xl text-5xl font-bold leading-[.98] tracking-[-.05em] sm:text-7xl">The right craft for <span className="gradient-text">the next move.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">Bring us the ambition, the constraint, or the messy middle. We bring the perspective and technical craft to make progress feel possible.</p><div className="mt-16 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map((service, index) => <Link href={`/services/${service.slug}`} key={service.slug} className="group rounded-3xl border border-border/70 bg-card/60 p-7 transition-colors hover:border-primary/60"><span className="font-mono text-[10px] text-primary">0{index + 1}</span><h2 className="mt-12 text-2xl font-semibold">{service.title}</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">{service.text}</p><span className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-primary">Explore service <ArrowUpRight size={16} /></span></Link>)}</div></section></main>
}
