'use client'

import { motion } from 'framer-motion'
import { ArrowUpRight, Globe2, HeartHandshake, Lightbulb, MapPin, ShieldCheck, Sparkles, Target, Users } from 'lucide-react'

const values = [
  { icon: Target, title: 'Clarity over noise', text: 'We find the essential question, then build toward it with intention.' },
  { icon: HeartHandshake, title: 'Partnership by default', text: 'Your context matters. We work openly, collaboratively, and without ego.' },
  { icon: Lightbulb, title: 'Curiosity is craft', text: 'We stay close to emerging technology without chasing every trend.' },
  { icon: ShieldCheck, title: 'Built to endure', text: 'Every system should be understandable, resilient, and ready for its next chapter.' },
]

export default function AboutPage() {
  return <main className="min-h-screen overflow-hidden bg-background text-foreground">
    <div className="hero-mesh pointer-events-none fixed inset-0 opacity-40" /><div className="grid-lines pointer-events-none fixed inset-0 opacity-30" />
    <nav className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-6 py-7 lg:px-10"><a href="/" className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Sparkles size={18}/></span><span className="font-mono text-sm font-semibold tracking-[0.18em]">ARONIA<span className="text-primary">.</span></span></a><div className="hidden gap-7 text-sm text-muted-foreground md:flex"><a href="/about" className="text-foreground">About</a><a href="/portfolio">Portfolio</a><a href="/testimonials">Testimonials</a><a href="/pricing">Pricing</a></div><a href="/contact" className="inline-flex items-center gap-2 rounded-full border border-border px-4 py-2 text-sm hover:border-primary/70 hover:text-primary">Let&apos;s talk <ArrowUpRight size={15}/></a></nav>
    <section className="relative z-10 mx-auto max-w-7xl px-6 pb-24 pt-16 lg:px-10 lg:pb-36 lg:pt-28"><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.7}} className="max-w-4xl"><p className="eyebrow">Who we are / 03</p><h1 className="mt-5 text-balance text-5xl font-bold leading-[.98] tracking-[-.05em] sm:text-7xl lg:text-[7.5rem]">Technology with <span className="gradient-text">intention.</span></h1><p className="mt-8 max-w-2xl text-pretty text-lg leading-8 text-muted-foreground">Aronia Dynamics is a software consultancy for teams who believe the right technology can change the shape of a business.</p></motion.div>
      <div className="mt-20 grid gap-4 lg:grid-cols-3"><div className="glass-panel rounded-3xl p-8 lg:col-span-2"><p className="eyebrow">Our story</p><p className="mt-5 max-w-2xl text-2xl font-semibold leading-tight sm:text-3xl">We started with a simple conviction: complex digital work should feel human.</p><p className="mt-6 max-w-2xl leading-7 text-muted-foreground">From our studios in Bangladesh and the USA, we help ambitious organizations turn uncertainty into useful, elegant systems. Our team brings strategy, engineering, design, and AI into one thoughtful process.</p></div><div className="rounded-3xl border border-primary/30 bg-primary/10 p-8"><Globe2 className="text-primary" size={28}/><p className="mt-16 text-3xl font-semibold">Two studios.<br/><span className="gradient-text">One perspective.</span></p></div></div>
    </section>
    <section className="relative z-10 border-y border-border/70 bg-card/30"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-20 lg:grid-cols-2 lg:px-10 lg:py-28"><div><p className="eyebrow">Mission / Vision</p><h2 className="mt-5 text-4xl font-bold tracking-tight sm:text-6xl">Make better <span className="gradient-text">possible.</span></h2></div><div className="space-y-8 text-muted-foreground"><div className="flex gap-5"><span className="mt-1 text-primary"><Target size={22}/></span><div><h3 className="text-xl font-semibold text-foreground">Our mission</h3><p className="mt-2 leading-7">Give bold ideas the technical clarity and momentum they need to become real.</p></div></div><div className="flex gap-5"><span className="mt-1 text-primary"><Sparkles size={22}/></span><div><h3 className="text-xl font-semibold text-foreground">Our vision</h3><p className="mt-2 leading-7">A world where technology expands human potential instead of adding to the noise.</p></div></div></div></div></section>
    <section className="relative z-10 mx-auto max-w-7xl px-6 py-24 lg:px-10 lg:py-32"><div className="mb-12 flex items-end justify-between gap-6"><div><p className="eyebrow">What guides us</p><h2 className="mt-4 text-4xl font-bold sm:text-6xl">The way we <span className="gradient-text">work.</span></h2></div><Users className="hidden text-primary sm:block" size={38}/></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{values.map(({icon:Icon,title,text})=><motion.article whileHover={{y:-5}} key={title} className="service-card rounded-2xl border border-border/70 bg-card/60 p-6"><Icon className="text-primary" size={21}/><h3 className="mt-12 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></motion.article>)}</div><div className="mt-20 flex flex-col gap-5 border-t border-border/70 pt-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><span className="flex items-center gap-2"><MapPin size={16} className="text-primary"/> Dhaka + New York</span><a href="/contact" className="inline-flex items-center gap-2 font-semibold text-primary">Work with us <ArrowUpRight size={16}/></a></div></section>
  </main>
}
