'use client'

import { motion } from 'framer-motion'
import { ArrowUpRight, Check, Filter, Sparkles } from 'lucide-react'
import { useState } from 'react'

const projects = [
  { title: 'Nexa Health', type: 'Web Development', category: 'Web', text: 'A patient-first platform that made complex care journeys feel clear.', result: '42% faster onboarding' },
  { title: 'Atlas Intelligence', type: 'AI Systems', category: 'AI', text: 'An always-on decision layer turning operational data into useful answers.', result: '3x faster insights' },
  { title: 'Kite Commerce', type: 'App Development', category: 'Apps', text: 'A high-conversion commerce experience built for a new generation of shoppers.', result: '68% repeat purchase rate' },
  { title: 'Monument Bank', type: 'System Design', category: 'Systems', text: 'A secure digital foundation designed to scale with a modern financial product.', result: '99.99% uptime' },
  { title: 'Fieldnote', type: 'Data Analytics', category: 'Data', text: 'A calm, visual command center for teams managing distributed operations.', result: '14 hours saved weekly' },
  { title: 'Northstar SEO', type: 'SEO Services', category: 'Growth', text: 'A content and search system that turned expertise into discoverability.', result: '4.2x organic growth' },
]
const filters = ['All', 'Web', 'AI', 'Apps', 'Systems', 'Data', 'Growth']

export default function PortfolioPage() {
  const [active, setActive] = useState('All')
  const visible = active === 'All' ? projects : projects.filter((project) => project.category === active)
  return <main className="min-h-screen overflow-hidden bg-background text-foreground"><div className="hero-mesh pointer-events-none fixed inset-0 opacity-35"/><div className="grid-lines pointer-events-none fixed inset-0 opacity-25"/>
    <nav className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-6 py-7 lg:px-10"><a href="/" className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Sparkles size={18}/></span><span className="font-mono text-sm font-semibold tracking-[.18em]">ARONIA<span className="text-primary">.</span></span></a><div className="hidden gap-7 text-sm text-muted-foreground md:flex"><a href="/about">About</a><a href="/portfolio" className="text-foreground">Portfolio</a><a href="/testimonials">Testimonials</a><a href="/pricing">Pricing</a></div><a href="/contact" className="inline-flex items-center gap-2 rounded-full border border-border px-4 py-2 text-sm hover:border-primary/70 hover:text-primary">Let&apos;s talk <ArrowUpRight size={15}/></a></nav>
    <section className="relative z-10 mx-auto max-w-7xl px-6 pb-28 pt-16 lg:px-10 lg:pt-28"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="max-w-3xl"><p className="eyebrow">Selected work / 04</p><h1 className="mt-5 text-balance text-5xl font-bold leading-[.98] tracking-[-.05em] sm:text-7xl">Ideas made <span className="gradient-text">useful.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">A selection of systems, products, and partnerships that moved the right metrics.</p></motion.div><div className="mt-16 flex flex-wrap items-center gap-2 border-b border-border/70 pb-5"><Filter size={16} className="mr-2 text-primary"/>{filters.map((filter)=><button key={filter} onClick={()=>setActive(filter)} className={`rounded-full px-4 py-2 text-sm transition-colors ${active===filter?'bg-primary text-primary-foreground':'text-muted-foreground hover:bg-muted hover:text-foreground'}`}>{filter}</button>)}</div><motion.div layout className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{visible.map((project,index)=><a href={`/case-studies/${project.title.toLowerCase().replaceAll(' ', '-')}`} key={project.title}><motion.article layout initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:index*.04}} className="group flex min-h-[330px] flex-col rounded-3xl border border-border/70 bg-card/60 p-7 transition-colors hover:border-primary/60"><div className="flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[.18em] text-primary">{project.type}</span><ArrowUpRight className="text-muted-foreground transition-colors group-hover:text-primary" size={19}/></div><div className="mt-auto"><h2 className="text-2xl font-semibold tracking-tight">{project.title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{project.text}</p><div className="mt-6 flex items-center gap-2 text-sm font-medium"><span className="flex size-5 items-center justify-center rounded-full bg-primary/15 text-primary"><Check size={12}/></span>{project.result}</div></div></motion.article></a>)}</motion.div><div className="mt-24 rounded-3xl border border-primary/30 bg-card p-8 sm:p-12"><p className="eyebrow">Have a challenge?</p><div className="mt-4 flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><h2 className="max-w-xl text-3xl font-bold sm:text-5xl">Let&apos;s make your next case study.</h2><a href="/contact" className="glow-button inline-flex shrink-0 items-center justify-center gap-2 rounded-full bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground">Start a project <ArrowUpRight size={16}/></a></div></div></section>
  </main>
}
