export const services = [
  { slug: 'digital-system-consultancy', title: 'Digital System Consultancy', text: 'Turn complex operations into clear, scalable digital systems.', detail: 'We map the way your organization works, identify the highest-leverage opportunities, and create a practical roadmap from today’s constraints to tomorrow’s capability.' },
  { slug: 'app-development', title: 'App Development', text: 'High-performance mobile experiences built for how people live.', detail: 'From product definition to release, we design and build mobile experiences that feel natural, perform reliably, and give your team a foundation to keep improving.' },
  { slug: 'web-development', title: 'Web Development', text: 'Fast, purposeful websites that make your next chapter visible.', detail: 'We combine strong editorial structure, distinctive interaction design, and modern engineering to create websites that earn attention and turn it into action.' },
  { slug: 'software-development', title: 'Software Development', text: 'Reliable custom software that compounds your competitive edge.', detail: 'We build the tools your business actually needs, with clear architecture, thoughtful interfaces, and delivery practices that keep complexity under control.' },
  { slug: 'system-design', title: 'System Development & Design', text: 'Thoughtful architecture and interfaces built to evolve.', detail: 'We connect product thinking with technical architecture so your systems can support new users, new markets, and new ideas without constant reinvention.' },
  { slug: 'ai-systems', title: 'AI Systems', text: 'Personalized and office-based AI that works alongside your team.', detail: 'We turn promising AI use cases into dependable workflows with the right data, human oversight, and measurable outcomes.' },
  { slug: 'data-analytics', title: 'AI Data Analytics', text: 'Find the signal in your data and make decisions with confidence.', detail: 'We bring fragmented information together into useful reporting, analysis, and decision systems that help teams move with confidence.' },
  { slug: 'networking', title: 'Networking Design & Development', text: 'Secure, resilient infrastructure for a connected business.', detail: 'We design secure and maintainable network foundations that support distributed teams, critical applications, and business continuity.' },
  { slug: 'seo-services', title: 'SEO Services', text: 'Build discoverability that turns attention into momentum.', detail: 'We create a durable search strategy across technical foundations, content, and measurement so the right people can find you.' },
]

export const caseStudies = [
  { slug: 'nexa-health', title: 'Nexa Health', type: 'Web Development', result: '42% faster onboarding', challenge: 'Patients were facing a fragmented and confusing digital intake journey.', approach: 'We simplified the experience into a guided, accessible flow and connected it to a clearer internal workflow for care teams.', outcome: 'Nexa Health reduced onboarding friction and gave patients a calmer first interaction with the service.' },
  { slug: 'atlas-intelligence', title: 'Atlas Intelligence', type: 'AI Systems', result: '3x faster insights', challenge: 'Operational data lived across tools, making everyday decisions slower than they needed to be.', approach: 'We designed an AI-assisted decision layer that brought trusted answers and relevant context into one place.', outcome: 'Teams moved from searching through reports to acting on useful answers in the flow of work.' },
  { slug: 'kite-commerce', title: 'Kite Commerce', type: 'App Development', result: '68% repeat purchase rate', challenge: 'A growing commerce brand needed a faster, more personal mobile buying experience.', approach: 'We rebuilt the core journey around speed, clarity, and thoughtful post-purchase engagement.', outcome: 'The new experience helped Kite create stronger habits and a more valuable relationship with returning customers.' },
]
